CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NULL,
    created_on TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW(),
    updated_on TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW(),
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS passwords (
    id UUID NOT NULL PRIMARY_KEY,
    user_id UUID NOT NULL FOREIGN KEY REFERENCES users(id),
    password_hash TEXT NOT NULL,
    created_on TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW(),
    version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id UUID NOT NULL PRIMARY_KEY,
    user_id UUID NOT NULL FOREIGN KEY REFERENCES users(id),
    created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ended_on TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL
);